In [21]:
import pandas as pd
import os

In [22]:
# iterate through all the csv files in the directory and merge them into a single dataframe
directory = "snowball_out2"
merged_df = pd.DataFrame()

for file in os.listdir(directory):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(directory, file))
        if 'merged_df' in locals():
            merged_df = pd.concat([merged_df, df], ignore_index=True)
        else:
            merged_df = df

# save te file
merged_df.to_csv("snowball_out2.csv")
merged_df

,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,openalex,https://openalex.org/W7166575179,https://doi.org/10.20854/bujse.1919769,Serbest Metin Girdilerinden Anlamsal Kategori ...,Ezgi Gökdemir; Kemal Elci; Hazal Oğuz Azğüler,2026-06-29,2026,Beykent üniversitesi fen ve mühendislik bil...,article,E-satın alma platformlarında tedarikçilerin su...,; ;,0,True,https://dergipark.org.tr/tr/download/article-f...,https://doi.org/10.20854/bujse.1919769,Text and Document Classification Technologies;...,Teknoloji Arastirma ve Gelistirme Endustriyel ...,tr,"{""openalex_id"":""https:\/\/openalex.org\/W71665..."
1,openalex,https://openalex.org/W4403236901,https://doi.org/10.1111/ijmr.12381,Guidelines for Bibliometric‐Systematic Literat...,Giacomo Marzi; Marco Balzano; Andrea Caputo; M...,2024-10-07,2024,International Journal of Management Reviews,review,Abstract The steady increase in academic produ...,; ; ; ; ;,454,True,https://onlinelibrary.wiley.com/doi/pdfdirect/...,https://doi.org/10.1111/ijmr.12381,scientometrics and bibliometrics research,IMT School for Advanced Studies Lucca; Univers...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44032..."
2,openalex,https://openalex.org/W4392712508,https://doi.org/10.1016/j.apenergy.2024.122961,A machine learning-based two-stage approach fo...,Pınar Yunusoğlu; Fehmi Burçin Özsoydan; Bilge ...,2024-03-12,2024,Applied Energy,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ;,20,False,NaN,https://doi.org/10.1016/j.apenergy.2024.122961,Forest Biomass Utilization and Management; Env...,Dokuz Eylül University; Izmir University; Bakı...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43927..."
3,openalex,https://openalex.org/W4392343540,https://doi.org/10.1016/j.ijpe.2024.109203,Using inverse DEA and machine learning algorit...,Sheng-Wei Lin; Wen‐Min Lu,2024-03-03,2024,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ;,44,False,NaN,https://doi.org/10.1016/j.ijpe.2024.109203,Sustainable Supply Chain Management; Environme...,Chinese Culture University; National Defense U...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43923..."
4,openalex,https://openalex.org/W4391403959,https://doi.org/10.1080/00207543.2024.2305804,Implementation of digital twins in the food su...,Ying Huang; Abhijeet Ghadge; Nicola Yates,2024-01-31,2024,International Journal of Production Research,article,Digital Twins (DTs) hold significant promise i...,; ; ; ; ; ; ; ; ;,68,True,https://www.tandfonline.com/doi/pdf/10.1080/00...,https://doi.org/10.1080/00207543.2024.2305804,Digital Transformation in Industry; Food Suppl...,Cranfield University,en,"{""openalex_id"":""https:\/\/openalex.org\/W43914..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,openalex,https://openalex.org/W4414191861,https://doi.org/10.1080/00207543.2025.2553824,The internet of things in supply chain managem...,Ilias Vlachos; Gary Graham,2025-09-15,2025,International Journal of Production Research,review,The Internet of Things (IoT) was initially ado...,; ; ; ; ; ;,8,False,NaN,https://doi.org/10.1080/00207543.2025.2553824,Digital Transformation in Industry; Big Data a...,Liverpool John Moores University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
171,openalex,https://openalex.org/W4414119692,https://doi.org/10.1007/s12559-025-10495-1,Customer-Perceived Value and Social Media Anal...,Lucas Gabriel Zanon; Rafael Ferro Munhoz Arant...,2025-09-11,2025,Cognitive Computation,article,NaN,; ; ; ; ; ;,1,False,NaN,https://doi.org/10.1007/s12559-025-10495-1,Sentiment Analysis and Opinion Mining; Advance...,Universidade Federal do Triângulo Mineiro; Uni...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
172,openalex,https://openalex.org/W4414104022,https://doi.org/10.1080/00207543.2025.2555533,Optimal dynamic pricing strategy for non-durab...,Zhitang Li; Benjamin Lev,2025-09-10,2025,International Journal of Production Research,article,This study develops a dynamic pricing model fo...,; ;,4,False,NaN,https://doi.org/10.1080/00207543.2025.2555533,Innovation Diffusion and Forecasting; Game The...,Shenzhen University; Drexel University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
173,openalex,https://openalex.org/W4410093718,https://doi.org/10.4274/eajem.galenos.2025.37108,The Role of Serum Beta-Trace Protein in the Di...,Mehmet Yortanlı; Ramazan Köylü; Öznur Köylü; B...,2025-05-05,2025,Eurasian Journal of Emergency Medicine,article,Aim: This study aimed to evaluate the diagnost...,; ; ; ; ; ; ; ; ;,0,True,https://www.eajem.com/pdf/bb2eeae3-0e60-42a4-a...,https://doi.org/10.4274/eajem.galenos.2025.37108,Sepsis Diagnosis and Treatment; Neonatal and M...,NaN,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."
174,openalex,https://openalex.org/W4410035803,https://doi.org/10.1007/s41660-025-00520-z,A Multi-Objective Optimization Framework to De...,Omid Rezaei; Rashed Sahraeian; Seyed Mohammad ...,2025-05-02,2025,Process Integration and Optimization for Susta...,article,NaN,; ; ; ; ; ; ; ; ; ; ;,4,False,NaN,https://doi.org/10.1007/s41660-025-00520-z,Sustainable Supply Chain Management; Supply Ch...,Shahed University; University of Shahrood,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."

In [23]:
# check against existing dataset and remove duplicates
existing_dataset = pd.read_csv("fulltext-screened-dataset.csv")

merged_df = merged_df[~merged_df['source_id'].isin(existing_dataset['source_id'])]
duplicates_df = merged_df[merged_df['source_id'].isin(existing_dataset['source_id'])]
print(duplicates_df)

# save the final merged dataset
merged_df.to_csv("snowball_out2.csv")
merged_df

Empty DataFrame
Columns: [source_db, source_id, doi, title, authors, publication_date, publication_year, source_name, doc_type, abstract, keywords, cited_by_count, is_open_access, pdf_url, landing_url, categories, institutions, language, raw_json]
Index: []

,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,openalex,https://openalex.org/W7166575179,https://doi.org/10.20854/bujse.1919769,Serbest Metin Girdilerinden Anlamsal Kategori ...,Ezgi Gökdemir; Kemal Elci; Hazal Oğuz Azğüler,2026-06-29,2026,Beykent üniversitesi fen ve mühendislik bil...,article,E-satın alma platformlarında tedarikçilerin su...,; ;,0,True,https://dergipark.org.tr/tr/download/article-f...,https://doi.org/10.20854/bujse.1919769,Text and Document Classification Technologies;...,Teknoloji Arastirma ve Gelistirme Endustriyel ...,tr,"{""openalex_id"":""https:\/\/openalex.org\/W71665..."
1,openalex,https://openalex.org/W4403236901,https://doi.org/10.1111/ijmr.12381,Guidelines for Bibliometric‐Systematic Literat...,Giacomo Marzi; Marco Balzano; Andrea Caputo; M...,2024-10-07,2024,International Journal of Management Reviews,review,Abstract The steady increase in academic produ...,; ; ; ; ;,454,True,https://onlinelibrary.wiley.com/doi/pdfdirect/...,https://doi.org/10.1111/ijmr.12381,scientometrics and bibliometrics research,IMT School for Advanced Studies Lucca; Univers...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44032..."
2,openalex,https://openalex.org/W4392712508,https://doi.org/10.1016/j.apenergy.2024.122961,A machine learning-based two-stage approach fo...,Pınar Yunusoğlu; Fehmi Burçin Özsoydan; Bilge ...,2024-03-12,2024,Applied Energy,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ;,20,False,NaN,https://doi.org/10.1016/j.apenergy.2024.122961,Forest Biomass Utilization and Management; Env...,Dokuz Eylül University; Izmir University; Bakı...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43927..."
3,openalex,https://openalex.org/W4392343540,https://doi.org/10.1016/j.ijpe.2024.109203,Using inverse DEA and machine learning algorit...,Sheng-Wei Lin; Wen‐Min Lu,2024-03-03,2024,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ;,44,False,NaN,https://doi.org/10.1016/j.ijpe.2024.109203,Sustainable Supply Chain Management; Environme...,Chinese Culture University; National Defense U...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43923..."
4,openalex,https://openalex.org/W4391403959,https://doi.org/10.1080/00207543.2024.2305804,Implementation of digital twins in the food su...,Ying Huang; Abhijeet Ghadge; Nicola Yates,2024-01-31,2024,International Journal of Production Research,article,Digital Twins (DTs) hold significant promise i...,; ; ; ; ; ; ; ; ;,68,True,https://www.tandfonline.com/doi/pdf/10.1080/00...,https://doi.org/10.1080/00207543.2024.2305804,Digital Transformation in Industry; Food Suppl...,Cranfield University,en,"{""openalex_id"":""https:\/\/openalex.org\/W43914..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,openalex,https://openalex.org/W4414191861,https://doi.org/10.1080/00207543.2025.2553824,The internet of things in supply chain managem...,Ilias Vlachos; Gary Graham,2025-09-15,2025,International Journal of Production Research,review,The Internet of Things (IoT) was initially ado...,; ; ; ; ; ;,8,False,NaN,https://doi.org/10.1080/00207543.2025.2553824,Digital Transformation in Industry; Big Data a...,Liverpool John Moores University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
171,openalex,https://openalex.org/W4414119692,https://doi.org/10.1007/s12559-025-10495-1,Customer-Perceived Value and Social Media Anal...,Lucas Gabriel Zanon; Rafael Ferro Munhoz Arant...,2025-09-11,2025,Cognitive Computation,article,NaN,; ; ; ; ; ;,1,False,NaN,https://doi.org/10.1007/s12559-025-10495-1,Sentiment Analysis and Opinion Mining; Advance...,Universidade Federal do Triângulo Mineiro; Uni...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
172,openalex,https://openalex.org/W4414104022,https://doi.org/10.1080/00207543.2025.2555533,Optimal dynamic pricing strategy for non-durab...,Zhitang Li; Benjamin Lev,2025-09-10,2025,International Journal of Production Research,article,This study develops a dynamic pricing model fo...,; ;,4,False,NaN,https://doi.org/10.1080/00207543.2025.2555533,Innovation Diffusion and Forecasting; Game The...,Shenzhen University; Drexel University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
173,openalex,https://openalex.org/W4410093718,https://doi.org/10.4274/eajem.galenos.2025.37108,The Role of Serum Beta-Trace Protein in the Di...,Mehmet Yortanlı; Ramazan Köylü; Öznur Köylü; B...,2025-05-05,2025,Eurasian Journal of Emergency Medicine,article,Aim: This study aimed to evaluate the diagnost...,; ; ; ; ; ; ; ; ;,0,True,https://www.eajem.com/pdf/bb2eeae3-0e60-42a4-a...,https://doi.org/10.4274/eajem.galenos.2025.37108,Sepsis Diagnosis and Treatment; Neonatal and M...,NaN,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."
174,openalex,https://openalex.org/W4410035803,https://doi.org/10.1007/s41660-025-00520-z,A Multi-Objective Optimization Framework to De...,Omid Rezaei; Rashed Sahraeian; Seyed Mohammad ...,2025-05-02,2025,Process Integration and Optimization for Susta...,article,NaN,; ; ; ; ; ; ; ; ; ; ;,4,False,NaN,https://doi.org/10.1007/s41660-025-00520-z,Sustainable Supply Chain Management; Supply Ch...,Shahed University; University of Shahrood,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."

In [26]:
snowball_out1 = pd.read_csv("snowball_out.csv")
snowball_out1

,Unnamed: 0,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,0,openalex,https://openalex.org/W4405622544,https://doi.org/10.36948/ijfmr.2024.v06i06.32232,The Role of Prompt Engineering in Improving La...,Divya Lamba -,2024-12-15,2024,International Journal For Multidisciplinary Re...,article,Prompt engineering is an emerging discipline t...,; ; ; ; ; ; ; ; ; ; ; ; ;,2,True,https://www.ijfmr.com/papers/2024/6/32232.pdf,https://doi.org/10.36948/ijfmr.2024.v06i06.32232,Topic Modeling; Natural Language Processing Te...,Indira Gandhi Delhi Technical University for W...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44056..."
1,1,openalex,https://openalex.org/W4400530355,https://doi.org/10.1108/md-10-2023-1944,Artificial intelligence (AI) and strategic pla...,Roberto Biloslavo; David Edgar; Erhan Aydın; Ç...,2024-07-11,2024,Management Decision,article,Purpose This study demonstrates how artificial...,; ; ; ; ; ; ; ; ; ;,54,True,NaN,https://doi.org/10.1108/md-10-2023-1944,Digital Transformation in Industry; Big Data a...,Glasgow Caledonian University; IPAG Business S...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44005..."
2,2,openalex,https://openalex.org/W4389359039,https://doi.org/10.1007/s12525-023-00680-1,Generative artificial intelligence,Leonardo Banh; Gero Strobel,2023-12-01,2023,Electronic Markets,article,Abstract Recent developments in the field of a...,; ; ; ; ; ; ;,484,True,https://link.springer.com/content/pdf/10.1007/...,https://doi.org/10.1007/s12525-023-00680-1,Explainable Artificial Intelligence (XAI); Top...,University of Duisburg-Essen,en,"{""openalex_id"":""https:\/\/openalex.org\/W43893..."
3,3,openalex,https://openalex.org/W4387020206,https://doi.org/10.1365/s40702-023-01008-5,Ganzheitliche Wandlungsfähigkeit von Produktio...,Pia Bielitz; Nicole Jäpel; David Heik; Dirk Re...,2023-09-25,2023,HMD Praxis der Wirtschaftsinformatik,article,Zusammenfassung Wandlungsfähigkeit von Unterne...,; ; ; ;,6,True,https://link.springer.com/content/pdf/10.1365/...,https://doi.org/10.1365/s40702-023-01008-5,Flexible and Reconfigurable Manufacturing Syst...,Hochschule für Technik und Wirtschaft Dresden ...,de,"{""openalex_id"":""https:\/\/openalex.org\/W43870..."
4,4,openalex,https://openalex.org/W4386735721,https://doi.org/10.1515/zwf-2023-1112,Thesen zur Konvergenz von Trends und Technolog...,Simon F. Schäfer; Marian Süße; Steffen Ihlenfeldt,2023-09-01,2023,Zeitschrift für wirtschaftlichen Fabrikbetrieb,article,Abstract Die Fabrikplanung ist ein mehrdimensi...,; ;,4,False,NaN,https://doi.org/10.1515/zwf-2023-1112,Flexible and Reconfigurable Manufacturing Syst...,Technische Universität Dresden; Fraunhofer Ins...,de,"{""openalex_id"":""https:\/\/openalex.org\/W43867..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,515,openalex,https://openalex.org/W4416121589,https://doi.org/10.1007/s44196-025-00992-4,Optimizing Large Language Models in Distribute...,Mubarak Ahmad; Abdulkadhem A. Abdulkadhem; Uma...,2025-11-11,2025,International Journal of Computational Intelli...,article,This paper introduces a holistic and scalable ...,; ; ; ; ; ;,1,True,https://link.springer.com/content/pdf/10.1007/...,https://doi.org/10.1007/s44196-025-00992-4,Artificial Intelligence in Healthcare and Educ...,Jiangnan University; University of Swat; Unive...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44161..."
507,516,openalex,https://openalex.org/W4413180152,https://doi.org/10.1109/aiiot65859.2025.11105299,LLM-Powered AI Agent Systems and Their Applica...,Guannan Liang; Qianqian Tong,2025-05-28,2025,NaN,conference-paper,The emergence of Large Language Models (LLMs) ...,NaN,14,False,NaN,https://doi.org/10.1109/aiiot65859.2025.11105299,Reinforcement Learning in Robotics; Multi-Agen...,Greensboro College; University of North Caroli...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44131..."
508,517,openalex,https://openalex.org/W4410088404,https://doi.org/10.1016/j.autcon.2025.106243,Synchronization in prefabricated off-site fit-...,Haoran Ding; Ray Y. Zhong; George Q. Huang,2025-05-05,2025,Automation in Construction,article,NaN,; ; ; ; ; ; ; ; ;,0,False,NaN,https://doi.org/10.1016/j.autcon.2025.106243,Manufacturing Process and Optimization; Digita...,Hong Kong Polytechnic University; University o...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."
509,518,openalex,https://openalex.org/W4408920931,https://doi.org/10.1016/j.aei.2025.103268,User needs insights from UGC based on large la...,Wei Wei; Chenliang Hao; Zixin Wang,2025-03-28,2025,Advanced Engineering Informatics,article,NaN,; ;,16,False,NaN,https://doi.org/10.1016/j.aei.2025.103268,AI in Service Interactions; ICT in Developing ...,Beihang University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44089..."
510,519,openalex,https://openalex.org/W4406092350,https://doi.org/10.1016/j.mex.2025.103158,Deep learning driven silicon wafer defect segm...,Rohan Ingle; Aniket K. Shahade; Mayur Gaikwad;...,2025-01-06,2025,MethodsX,article,Integrated Circuits are made of various transi...,; ; ; ; ; ; ; ; ; ;,6,True,NaN,https://doi.org/10.1016/j.mex.2025.103158,Industrial Vision Systems and Defect Detection...,Symbiosis International University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44060..."

In [27]:
snowball_out2 = pd.read_csv("snowball_out2.csv")
snowball_out2

,Unnamed: 0,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,0,openalex,https://openalex.org/W7166575179,https://doi.org/10.20854/bujse.1919769,Serbest Metin Girdilerinden Anlamsal Kategori ...,Ezgi Gökdemir; Kemal Elci; Hazal Oğuz Azğüler,2026-06-29,2026,Beykent üniversitesi fen ve mühendislik bil...,article,E-satın alma platformlarında tedarikçilerin su...,; ;,0,True,https://dergipark.org.tr/tr/download/article-f...,https://doi.org/10.20854/bujse.1919769,Text and Document Classification Technologies;...,Teknoloji Arastirma ve Gelistirme Endustriyel ...,tr,"{""openalex_id"":""https:\/\/openalex.org\/W71665..."
1,1,openalex,https://openalex.org/W4403236901,https://doi.org/10.1111/ijmr.12381,Guidelines for Bibliometric‐Systematic Literat...,Giacomo Marzi; Marco Balzano; Andrea Caputo; M...,2024-10-07,2024,International Journal of Management Reviews,review,Abstract The steady increase in academic produ...,; ; ; ; ;,454,True,https://onlinelibrary.wiley.com/doi/pdfdirect/...,https://doi.org/10.1111/ijmr.12381,scientometrics and bibliometrics research,IMT School for Advanced Studies Lucca; Univers...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44032..."
2,2,openalex,https://openalex.org/W4392712508,https://doi.org/10.1016/j.apenergy.2024.122961,A machine learning-based two-stage approach fo...,Pınar Yunusoğlu; Fehmi Burçin Özsoydan; Bilge ...,2024-03-12,2024,Applied Energy,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ;,20,False,NaN,https://doi.org/10.1016/j.apenergy.2024.122961,Forest Biomass Utilization and Management; Env...,Dokuz Eylül University; Izmir University; Bakı...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43927..."
3,3,openalex,https://openalex.org/W4392343540,https://doi.org/10.1016/j.ijpe.2024.109203,Using inverse DEA and machine learning algorit...,Sheng-Wei Lin; Wen‐Min Lu,2024-03-03,2024,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ;,44,False,NaN,https://doi.org/10.1016/j.ijpe.2024.109203,Sustainable Supply Chain Management; Environme...,Chinese Culture University; National Defense U...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43923..."
4,4,openalex,https://openalex.org/W4391403959,https://doi.org/10.1080/00207543.2024.2305804,Implementation of digital twins in the food su...,Ying Huang; Abhijeet Ghadge; Nicola Yates,2024-01-31,2024,International Journal of Production Research,article,Digital Twins (DTs) hold significant promise i...,; ; ; ; ; ; ; ; ;,68,True,https://www.tandfonline.com/doi/pdf/10.1080/00...,https://doi.org/10.1080/00207543.2024.2305804,Digital Transformation in Industry; Food Suppl...,Cranfield University,en,"{""openalex_id"":""https:\/\/openalex.org\/W43914..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,170,openalex,https://openalex.org/W4414191861,https://doi.org/10.1080/00207543.2025.2553824,The internet of things in supply chain managem...,Ilias Vlachos; Gary Graham,2025-09-15,2025,International Journal of Production Research,review,The Internet of Things (IoT) was initially ado...,; ; ; ; ; ;,8,False,NaN,https://doi.org/10.1080/00207543.2025.2553824,Digital Transformation in Industry; Big Data a...,Liverpool John Moores University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
171,171,openalex,https://openalex.org/W4414119692,https://doi.org/10.1007/s12559-025-10495-1,Customer-Perceived Value and Social Media Anal...,Lucas Gabriel Zanon; Rafael Ferro Munhoz Arant...,2025-09-11,2025,Cognitive Computation,article,NaN,; ; ; ; ; ;,1,False,NaN,https://doi.org/10.1007/s12559-025-10495-1,Sentiment Analysis and Opinion Mining; Advance...,Universidade Federal do Triângulo Mineiro; Uni...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
172,172,openalex,https://openalex.org/W4414104022,https://doi.org/10.1080/00207543.2025.2555533,Optimal dynamic pricing strategy for non-durab...,Zhitang Li; Benjamin Lev,2025-09-10,2025,International Journal of Production Research,article,This study develops a dynamic pricing model fo...,; ;,4,False,NaN,https://doi.org/10.1080/00207543.2025.2555533,Innovation Diffusion and Forecasting; Game The...,Shenzhen University; Drexel University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
173,173,openalex,https://openalex.org/W4410093718,https://doi.org/10.4274/eajem.galenos.2025.37108,The Role of Serum Beta-Trace Protein in the Di...,Mehmet Yortanlı; Ramazan Köylü; Öznur Köylü; B...,2025-05-05,2025,Eurasian Journal of Emergency Medicine,article,Aim: This study aimed to evaluate the diagnost...,; ; ; ; ; ; ; ; ;,0,True,https://www.eajem.com/pdf/bb2eeae3-0e60-42a4-a...,https://doi.org/10.4274/eajem.galenos.2025.37108,Sepsis Diagnosis and Treatment; Neonatal and M...,NaN,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."
174,174,openalex,https://openalex.org/W4410035803,https://doi.org/10.1007/s41660-025-00520-z,A Multi-Objective Optimization Framework to De...,Omid Rezaei; Rashed Sahraeian; Seyed Mohammad ...,2025-05-02,2025,Process Integration and Optimization for Susta...,article,NaN,; ; ; ; ; ; ; ; ; ; ;,4,False,NaN,https://doi.org/10.1007/s41660-025-00520-z,Sustainable Supply Chain Management; Supply Ch...,Shahed University; University of Shahrood,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."

In [30]:
merged_df = snowball_out2[~snowball_out2["source_id"].isin(snowball_out1['source_id'])]
merged_df.to_csv("snowball_out2.csv")
merged_df

,Unnamed: 0,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,0,openalex,https://openalex.org/W7166575179,https://doi.org/10.20854/bujse.1919769,Serbest Metin Girdilerinden Anlamsal Kategori ...,Ezgi Gökdemir; Kemal Elci; Hazal Oğuz Azğüler,2026-06-29,2026,Beykent üniversitesi fen ve mühendislik bil...,article,E-satın alma platformlarında tedarikçilerin su...,; ;,0,True,https://dergipark.org.tr/tr/download/article-f...,https://doi.org/10.20854/bujse.1919769,Text and Document Classification Technologies;...,Teknoloji Arastirma ve Gelistirme Endustriyel ...,tr,"{""openalex_id"":""https:\/\/openalex.org\/W71665..."
2,2,openalex,https://openalex.org/W4392712508,https://doi.org/10.1016/j.apenergy.2024.122961,A machine learning-based two-stage approach fo...,Pınar Yunusoğlu; Fehmi Burçin Özsoydan; Bilge ...,2024-03-12,2024,Applied Energy,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ;,20,False,NaN,https://doi.org/10.1016/j.apenergy.2024.122961,Forest Biomass Utilization and Management; Env...,Dokuz Eylül University; Izmir University; Bakı...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43927..."
6,6,openalex,https://openalex.org/W4388869538,https://doi.org/10.1111/jbl.12367,Retail &amp; wholesale inventories: A literatu...,Micah J. Marzolf; Jason Miller; Simone T. Pein...,2023-11-20,2023,Journal of Business Logistics,article,Abstract Efficient management of inventories i...,; ; ; ; ; ; ; ; ; ;,22,True,https://onlinelibrary.wiley.com/doi/pdfdirect/...,https://doi.org/10.1111/jbl.12367,Supply Chain and Inventory Management; Sustain...,Iowa State University; Michigan State University,en,"{""openalex_id"":""https:\/\/openalex.org\/W43888..."
8,8,openalex,https://openalex.org/W4388223983,https://doi.org/10.1080/00207543.2023.2276811,From natural language to simulations: applying...,Ilya Jackson; María Jesús Sáenz; Dmitry Ivanov,2023-11-02,2023,International Journal of Production Research,article,Our research strives to examine how simulation...,; ; ; ; ; ; ; ; ; ; ; ; ;,153,True,https://www.tandfonline.com/doi/pdf/10.1080/00...,https://doi.org/10.1080/00207543.2023.2276811,Data Quality and Management; Business Process ...,Berlin School of Economics and Law; Massachuse...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43882..."
10,10,openalex,https://openalex.org/W4387408304,https://doi.org/10.1016/j.eswa.2023.122001,Discovering stop and parking behaviors of last...,Marta Galende; G.I. Sainz-Palmero; M.J. Fuente,2023-10-06,2023,Expert Systems with Applications,article,NaN,; ; ; ; ; ; ; ; ; ; ; ;,12,True,https://www.sciencedirect.com/science/article/...,https://doi.org/10.1016/j.eswa.2023.122001,Smart Parking Systems Research; Urban and Frei...,Centro Tecnológico del Mar; Universidad de Val...,en,"{""openalex_id"":""https:\/\/openalex.org\/W43874..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,170,openalex,https://openalex.org/W4414191861,https://doi.org/10.1080/00207543.2025.2553824,The internet of things in supply chain managem...,Ilias Vlachos; Gary Graham,2025-09-15,2025,International Journal of Production Research,review,The Internet of Things (IoT) was initially ado...,; ; ; ; ; ;,8,False,NaN,https://doi.org/10.1080/00207543.2025.2553824,Digital Transformation in Industry; Big Data a...,Liverpool John Moores University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
171,171,openalex,https://openalex.org/W4414119692,https://doi.org/10.1007/s12559-025-10495-1,Customer-Perceived Value and Social Media Anal...,Lucas Gabriel Zanon; Rafael Ferro Munhoz Arant...,2025-09-11,2025,Cognitive Computation,article,NaN,; ; ; ; ; ;,1,False,NaN,https://doi.org/10.1007/s12559-025-10495-1,Sentiment Analysis and Opinion Mining; Advance...,Universidade Federal do Triângulo Mineiro; Uni...,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
172,172,openalex,https://openalex.org/W4414104022,https://doi.org/10.1080/00207543.2025.2555533,Optimal dynamic pricing strategy for non-durab...,Zhitang Li; Benjamin Lev,2025-09-10,2025,International Journal of Production Research,article,This study develops a dynamic pricing model fo...,; ;,4,False,NaN,https://doi.org/10.1080/00207543.2025.2555533,Innovation Diffusion and Forecasting; Game The...,Shenzhen University; Drexel University,en,"{""openalex_id"":""https:\/\/openalex.org\/W44141..."
173,173,openalex,https://openalex.org/W4410093718,https://doi.org/10.4274/eajem.galenos.2025.37108,The Role of Serum Beta-Trace Protein in the Di...,Mehmet Yortanlı; Ramazan Köylü; Öznur Köylü; B...,2025-05-05,2025,Eurasian Journal of Emergency Medicine,article,Aim: This study aimed to evaluate the diagnost...,; ; ; ; ; ; ; ; ;,0,True,https://www.eajem.com/pdf/bb2eeae3-0e60-42a4-a...,https://doi.org/10.4274/eajem.galenos.2025.37108,Sepsis Diagnosis and Treatment; Neonatal and M...,NaN,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."
174,174,openalex,https://openalex.org/W4410035803,https://doi.org/10.1007/s41660-025-00520-z,A Multi-Objective Optimization Framework to De...,Omid Rezaei; Rashed Sahraeian; Seyed Mohammad ...,2025-05-02,2025,Process Integration and Optimization for Susta...,article,NaN,; ; ; ; ; ; ; ; ; ; ;,4,False,NaN,https://doi.org/10.1007/s41660-025-00520-z,Sustainable Supply Chain Management; Supply Ch...,Shahed University; University of Shahrood,en,"{""openalex_id"":""https:\/\/openalex.org\/W44100..."