In [12]:
import pandas as pd
import os

In [13]:
# iterate through all the csv files in the directory and merge them into a single dataframe
directory = "snowball_out"
merged_df = pd.DataFrame()

for file in os.listdir(directory):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(directory, file))
        if 'merged_df' in locals():
            merged_df = pd.concat([merged_df, df], ignore_index=True)
        else:
            merged_df = df

# save te file
merged_df.to_csv("snowball_out.csv")
merged_df

,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,openalex,https://openalex.org/W7170031172,https://doi.org/10.1007/s00170-026-18711-4,Large language models in manufacturing: a comp...,Mazdak Maghanaki; Mohammad Shahin; F. Frank Chen,2026-07-23,2026,The International Journal of Advanced Manufact...,article,Large Language Models (LLMs) have become trans...,; ; ;,0,True,https://link.springer.com/content/pdf/10.1007/...,https://doi.org/10.1007/s00170-026-18711-4,Digital Transformation in Industry; Machine Le...,The University of Texas at San Antonio; Cornel...,en,"{""openalex_id"":""https:\/\/openalex.org\/W71700..."
1,openalex,https://openalex.org/W7150213031,https://doi.org/10.1080/19401493.2026.2653969,MCP-enabled agentic AI workflow for building e...,Han Li; Liang Zhang; Huiwen Zhou; Tianzhen Hong,2026-04-05,2026,Journal of Building Performance Simulation,article,Traditional building energy modelling workflow...,; ; ; ; ;,1,True,NaN,https://doi.org/10.1080/19401493.2026.2653969,Building Energy and Comfort Optimization; Mode...,University of Arizona; Lawrence Berkeley Natio...,en,"{""openalex_id"":""https:\/\/openalex.org\/W71502..."
2,openalex,https://openalex.org/W7136300628,https://doi.org/10.1145/3801961,Large Language Models for Combinatorial Optimi...,Francesca Da Ros; Michael Soprano; Luca Di Gas...,2026-03-16,2026,ACM Computing Surveys,article,This systematic review explores the applicatio...,; ; ; ; ;,0,True,NaN,https://doi.org/10.1145/3801961,Constraint Satisfaction and Optimization; Arti...,University of Udine,en,"{""openalex_id"":""https:\/\/openalex.org\/W71363..."
3,openalex,https://openalex.org/W4415344803,https://doi.org/10.1145/3801961,Large Language Models for Combinatorial Optimi...,Francesca Da Ros; Michael Soprano; Luca Di Gas...,2026-03-16,2026,ACM Computing Surveys,review,This systematic review explores the applicatio...,; ; ; ; ;,8,True,NaN,https://doi.org/10.1145/3801961,Topic Modeling; Natural Language Processing Te...,University of Udine,en,"{""openalex_id"":""https:\/\/openalex.org\/W44153..."
4,openalex,https://openalex.org/W7124697892,https://doi.org/10.1007/s44443-025-00458-9,Inventory optimization under supply chain disr...,Ruijing Wu,2026-01-19,2026,Journal of King Saud University - Computer and...,article,Abstract This study pioneers the integration o...,; ; ; ; ; ; ;,0,True,NaN,https://doi.org/10.1007/s44443-025-00458-9,Supply Chain Resilience and Risk Management; S...,Shanghai International Studies University,en,"{""openalex_id"":""https:\/\/openalex.org\/W71246..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,openalex,https://openalex.org/W2009448384,https://doi.org/10.1016/j.indmarman.2005.01.004,"Formal governance mechanisms, relational gover...",Chwo‐Ming Joseph Yu; Tsai-Ju Liao; Zheng-Dao Lin,2005-06-10,2005,Industrial Marketing Management,article,NaN,; ; ; ; ; ; ;,188,False,NaN,https://doi.org/10.1016/j.indmarman.2005.01.004,Outsourcing and Supply Chain Management; Innov...,National Chengchi University,en,"{""openalex_id"":""https:\/\/openalex.org\/W20094..."
722,openalex,https://openalex.org/W2108380201,https://doi.org/10.1108/13673270510582983,A knowledge‐based system to support procuremen...,H.C.W. Lau; Andrew Ning; K.F. Pun; Kwai‐Sang C...,2005-02-01,2005,Journal of Knowledge Management,article,Purpose – To propose an infrastructure of a kn...,; ; ; ; ; ; ; ; ; ; ;,46,False,NaN,https://doi.org/10.1108/13673270510582983,Big Data and Business Intelligence,University of the West Indies; University of t...,en,"{""openalex_id"":""https:\/\/openalex.org\/W21083..."
723,openalex,https://openalex.org/W2003965326,https://doi.org/10.1016/s0925-5273(03)00128-2,The impact of forecasting methods on the bullw...,Xiaolong Zhang,2003-10-09,2003,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;,276,False,NaN,https://doi.org/10.1016/s0925-5273(03)00128-2,Supply Chain and Inventory Management; Forecas...,Fairleigh Dickinson University,en,"{""openalex_id"":""https:\/\/openalex.org\/W20039..."
724,openalex,https://openalex.org/W2070410573,https://doi.org/10.1016/s0925-5273(00)00156-0,Inventory management in supply chains: a reinf...,Ilaria Giannoccaro; Pierpaolo Pontrandolfo,2002-07-01,2002,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;,221,False,NaN,https://doi.org/10.1016/s0925-5273(00)00156-0,Supply Chain and Inventory Management; Sustain...,Polytechnic University of Bari,en,"{""openalex_id"":""https:\/\/openalex.org\/W20704..."
725,openalex,https://openalex.org/W2170895557,https://doi.org/10.1016/s0377-2217(99)00237-4,A novel decomposition approach for on-line lot...,Emile Aarts; M.F. Reijnhoudt; H.P. Stehouwer; ...,2000-04-01,2000,European Journal of Operational Research,article,NaN,; ; ; ; ; ; ; ;,14,True,NaN,https://doi.org/10.1016/s0377-2217(99)00237-4,Supply Chain and Inventory Management; Consume...,Eindhoven University of Technology; Philips (N...,en,"{""openalex_id"":""https:\/\/openalex.org\/W21708..."

In [14]:
# check against existing dataset and remove duplicates
existing_dataset = pd.read_csv("fulltext-screened-dataset.csv")

merged_df = merged_df[~merged_df['source_id'].isin(existing_dataset['source_id'])]
duplicates_df = merged_df[merged_df['source_id'].isin(existing_dataset['source_id'])]
print(duplicates_df)

# save the final merged dataset
merged_df.to_csv("snowball_out.csv")
merged_df

Empty DataFrame
Columns: [source_db, source_id, doi, title, authors, publication_date, publication_year, source_name, doc_type, abstract, keywords, cited_by_count, is_open_access, pdf_url, landing_url, categories, institutions, language, raw_json]
Index: []

,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,openalex,https://openalex.org/W7170031172,https://doi.org/10.1007/s00170-026-18711-4,Large language models in manufacturing: a comp...,Mazdak Maghanaki; Mohammad Shahin; F. Frank Chen,2026-07-23,2026,The International Journal of Advanced Manufact...,article,Large Language Models (LLMs) have become trans...,; ; ;,0,True,https://link.springer.com/content/pdf/10.1007/...,https://doi.org/10.1007/s00170-026-18711-4,Digital Transformation in Industry; Machine Le...,The University of Texas at San Antonio; Cornel...,en,"{""openalex_id"":""https:\/\/openalex.org\/W71700..."
1,openalex,https://openalex.org/W7150213031,https://doi.org/10.1080/19401493.2026.2653969,MCP-enabled agentic AI workflow for building e...,Han Li; Liang Zhang; Huiwen Zhou; Tianzhen Hong,2026-04-05,2026,Journal of Building Performance Simulation,article,Traditional building energy modelling workflow...,; ; ; ; ;,1,True,NaN,https://doi.org/10.1080/19401493.2026.2653969,Building Energy and Comfort Optimization; Mode...,University of Arizona; Lawrence Berkeley Natio...,en,"{""openalex_id"":""https:\/\/openalex.org\/W71502..."
2,openalex,https://openalex.org/W7136300628,https://doi.org/10.1145/3801961,Large Language Models for Combinatorial Optimi...,Francesca Da Ros; Michael Soprano; Luca Di Gas...,2026-03-16,2026,ACM Computing Surveys,article,This systematic review explores the applicatio...,; ; ; ; ;,0,True,NaN,https://doi.org/10.1145/3801961,Constraint Satisfaction and Optimization; Arti...,University of Udine,en,"{""openalex_id"":""https:\/\/openalex.org\/W71363..."
3,openalex,https://openalex.org/W4415344803,https://doi.org/10.1145/3801961,Large Language Models for Combinatorial Optimi...,Francesca Da Ros; Michael Soprano; Luca Di Gas...,2026-03-16,2026,ACM Computing Surveys,review,This systematic review explores the applicatio...,; ; ; ; ;,8,True,NaN,https://doi.org/10.1145/3801961,Topic Modeling; Natural Language Processing Te...,University of Udine,en,"{""openalex_id"":""https:\/\/openalex.org\/W44153..."
4,openalex,https://openalex.org/W7124697892,https://doi.org/10.1007/s44443-025-00458-9,Inventory optimization under supply chain disr...,Ruijing Wu,2026-01-19,2026,Journal of King Saud University - Computer and...,article,Abstract This study pioneers the integration o...,; ; ; ; ; ; ;,0,True,NaN,https://doi.org/10.1007/s44443-025-00458-9,Supply Chain Resilience and Risk Management; S...,Shanghai International Studies University,en,"{""openalex_id"":""https:\/\/openalex.org\/W71246..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,openalex,https://openalex.org/W2009448384,https://doi.org/10.1016/j.indmarman.2005.01.004,"Formal governance mechanisms, relational gover...",Chwo‐Ming Joseph Yu; Tsai-Ju Liao; Zheng-Dao Lin,2005-06-10,2005,Industrial Marketing Management,article,NaN,; ; ; ; ; ; ;,188,False,NaN,https://doi.org/10.1016/j.indmarman.2005.01.004,Outsourcing and Supply Chain Management; Innov...,National Chengchi University,en,"{""openalex_id"":""https:\/\/openalex.org\/W20094..."
722,openalex,https://openalex.org/W2108380201,https://doi.org/10.1108/13673270510582983,A knowledge‐based system to support procuremen...,H.C.W. Lau; Andrew Ning; K.F. Pun; Kwai‐Sang C...,2005-02-01,2005,Journal of Knowledge Management,article,Purpose – To propose an infrastructure of a kn...,; ; ; ; ; ; ; ; ; ; ;,46,False,NaN,https://doi.org/10.1108/13673270510582983,Big Data and Business Intelligence,University of the West Indies; University of t...,en,"{""openalex_id"":""https:\/\/openalex.org\/W21083..."
723,openalex,https://openalex.org/W2003965326,https://doi.org/10.1016/s0925-5273(03)00128-2,The impact of forecasting methods on the bullw...,Xiaolong Zhang,2003-10-09,2003,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;,276,False,NaN,https://doi.org/10.1016/s0925-5273(03)00128-2,Supply Chain and Inventory Management; Forecas...,Fairleigh Dickinson University,en,"{""openalex_id"":""https:\/\/openalex.org\/W20039..."
724,openalex,https://openalex.org/W2070410573,https://doi.org/10.1016/s0925-5273(00)00156-0,Inventory management in supply chains: a reinf...,Ilaria Giannoccaro; Pierpaolo Pontrandolfo,2002-07-01,2002,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;,221,False,NaN,https://doi.org/10.1016/s0925-5273(00)00156-0,Supply Chain and Inventory Management; Sustain...,Polytechnic University of Bari,en,"{""openalex_id"":""https:\/\/openalex.org\/W20704..."
725,openalex,https://openalex.org/W2170895557,https://doi.org/10.1016/s0377-2217(99)00237-4,A novel decomposition approach for on-line lot...,Emile Aarts; M.F. Reijnhoudt; H.P. Stehouwer; ...,2000-04-01,2000,European Journal of Operational Research,article,NaN,; ; ; ; ; ; ; ;,14,True,NaN,https://doi.org/10.1016/s0377-2217(99)00237-4,Supply Chain and Inventory Management; Consume...,Eindhoven University of Technology; Philips (N...,en,"{""openalex_id"":""https:\/\/openalex.org\/W21708..."

In [9]:
snowball_out1 = pd.read_csv("snowball_out.csv")
snowball_out1

,Unnamed: 0,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,0,openalex,https://openalex.org/W7170031172,https://doi.org/10.1007/s00170-026-18711-4,Large language models in manufacturing: a comp...,Mazdak Maghanaki; Mohammad Shahin; F. Frank Chen,2026-07-23,2026,The International Journal of Advanced Manufact...,article,Large Language Models (LLMs) have become trans...,; ; ;,0,True,https://link.springer.com/content/pdf/10.1007/...,https://doi.org/10.1007/s00170-026-18711-4,Digital Transformation in Industry; Machine Le...,The University of Texas at San Antonio; Cornel...,en,"{""openalex_id"":""https:\/\/openalex.org\/W71700..."
1,1,openalex,https://openalex.org/W7150213031,https://doi.org/10.1080/19401493.2026.2653969,MCP-enabled agentic AI workflow for building e...,Han Li; Liang Zhang; Huiwen Zhou; Tianzhen Hong,2026-04-05,2026,Journal of Building Performance Simulation,article,Traditional building energy modelling workflow...,; ; ; ; ;,1,True,NaN,https://doi.org/10.1080/19401493.2026.2653969,Building Energy and Comfort Optimization; Mode...,University of Arizona; Lawrence Berkeley Natio...,en,"{""openalex_id"":""https:\/\/openalex.org\/W71502..."
2,2,openalex,https://openalex.org/W7136300628,https://doi.org/10.1145/3801961,Large Language Models for Combinatorial Optimi...,Francesca Da Ros; Michael Soprano; Luca Di Gas...,2026-03-16,2026,ACM Computing Surveys,article,This systematic review explores the applicatio...,; ; ; ; ;,0,True,NaN,https://doi.org/10.1145/3801961,Constraint Satisfaction and Optimization; Arti...,University of Udine,en,"{""openalex_id"":""https:\/\/openalex.org\/W71363..."
3,3,openalex,https://openalex.org/W4415344803,https://doi.org/10.1145/3801961,Large Language Models for Combinatorial Optimi...,Francesca Da Ros; Michael Soprano; Luca Di Gas...,2026-03-16,2026,ACM Computing Surveys,review,This systematic review explores the applicatio...,; ; ; ; ;,8,True,NaN,https://doi.org/10.1145/3801961,Topic Modeling; Natural Language Processing Te...,University of Udine,en,"{""openalex_id"":""https:\/\/openalex.org\/W44153..."
4,4,openalex,https://openalex.org/W7124697892,https://doi.org/10.1007/s44443-025-00458-9,Inventory optimization under supply chain disr...,Ruijing Wu,2026-01-19,2026,Journal of King Saud University - Computer and...,article,Abstract This study pioneers the integration o...,; ; ; ; ; ; ;,0,True,NaN,https://doi.org/10.1007/s44443-025-00458-9,Supply Chain Resilience and Risk Management; S...,Shanghai International Studies University,en,"{""openalex_id"":""https:\/\/openalex.org\/W71246..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,721,openalex,https://openalex.org/W2009448384,https://doi.org/10.1016/j.indmarman.2005.01.004,"Formal governance mechanisms, relational gover...",Chwo‐Ming Joseph Yu; Tsai-Ju Liao; Zheng-Dao Lin,2005-06-10,2005,Industrial Marketing Management,article,NaN,; ; ; ; ; ; ;,188,False,NaN,https://doi.org/10.1016/j.indmarman.2005.01.004,Outsourcing and Supply Chain Management; Innov...,National Chengchi University,en,"{""openalex_id"":""https:\/\/openalex.org\/W20094..."
708,722,openalex,https://openalex.org/W2108380201,https://doi.org/10.1108/13673270510582983,A knowledge‐based system to support procuremen...,H.C.W. Lau; Andrew Ning; K.F. Pun; Kwai‐Sang C...,2005-02-01,2005,Journal of Knowledge Management,article,Purpose – To propose an infrastructure of a kn...,; ; ; ; ; ; ; ; ; ; ;,46,False,NaN,https://doi.org/10.1108/13673270510582983,Big Data and Business Intelligence,University of the West Indies; University of t...,en,"{""openalex_id"":""https:\/\/openalex.org\/W21083..."
709,723,openalex,https://openalex.org/W2003965326,https://doi.org/10.1016/s0925-5273(03)00128-2,The impact of forecasting methods on the bullw...,Xiaolong Zhang,2003-10-09,2003,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;,276,False,NaN,https://doi.org/10.1016/s0925-5273(03)00128-2,Supply Chain and Inventory Management; Forecas...,Fairleigh Dickinson University,en,"{""openalex_id"":""https:\/\/openalex.org\/W20039..."
710,724,openalex,https://openalex.org/W2070410573,https://doi.org/10.1016/s0925-5273(00)00156-0,Inventory management in supply chains: a reinf...,Ilaria Giannoccaro; Pierpaolo Pontrandolfo,2002-07-01,2002,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;,221,False,NaN,https://doi.org/10.1016/s0925-5273(00)00156-0,Supply Chain and Inventory Management; Sustain...,Polytechnic University of Bari,en,"{""openalex_id"":""https:\/\/openalex.org\/W20704..."
711,725,openalex,https://openalex.org/W2170895557,https://doi.org/10.1016/s0377-2217(99)00237-4,A novel decomposition approach for on-line lot...,Emile Aarts; M.F. Reijnhoudt; H.P. Stehouwer; ...,2000-04-01,2000,European Journal of Operational Research,article,NaN,; ; ; ; ; ; ; ;,14,True,NaN,https://doi.org/10.1016/s0377-2217(99)00237-4,Supply Chain and Inventory Management; Consume...,Eindhoven University of Technology; Philips (N...,en,"{""openalex_id"":""https:\/\/openalex.org\/W21708..."

In [10]:
snowball_out2 = pd.read_csv("snowball_out.csv")
snowball_out2

,Unnamed: 0,source_db,source_id,doi,title,authors,publication_date,publication_year,source_name,doc_type,abstract,keywords,cited_by_count,is_open_access,pdf_url,landing_url,categories,institutions,language,raw_json
0,0,openalex,https://openalex.org/W7170031172,https://doi.org/10.1007/s00170-026-18711-4,Large language models in manufacturing: a comp...,Mazdak Maghanaki; Mohammad Shahin; F. Frank Chen,2026-07-23,2026,The International Journal of Advanced Manufact...,article,Large Language Models (LLMs) have become trans...,; ; ;,0,True,https://link.springer.com/content/pdf/10.1007/...,https://doi.org/10.1007/s00170-026-18711-4,Digital Transformation in Industry; Machine Le...,The University of Texas at San Antonio; Cornel...,en,"{""openalex_id"":""https:\/\/openalex.org\/W71700..."
1,1,openalex,https://openalex.org/W7150213031,https://doi.org/10.1080/19401493.2026.2653969,MCP-enabled agentic AI workflow for building e...,Han Li; Liang Zhang; Huiwen Zhou; Tianzhen Hong,2026-04-05,2026,Journal of Building Performance Simulation,article,Traditional building energy modelling workflow...,; ; ; ; ;,1,True,NaN,https://doi.org/10.1080/19401493.2026.2653969,Building Energy and Comfort Optimization; Mode...,University of Arizona; Lawrence Berkeley Natio...,en,"{""openalex_id"":""https:\/\/openalex.org\/W71502..."
2,2,openalex,https://openalex.org/W7136300628,https://doi.org/10.1145/3801961,Large Language Models for Combinatorial Optimi...,Francesca Da Ros; Michael Soprano; Luca Di Gas...,2026-03-16,2026,ACM Computing Surveys,article,This systematic review explores the applicatio...,; ; ; ; ;,0,True,NaN,https://doi.org/10.1145/3801961,Constraint Satisfaction and Optimization; Arti...,University of Udine,en,"{""openalex_id"":""https:\/\/openalex.org\/W71363..."
3,3,openalex,https://openalex.org/W4415344803,https://doi.org/10.1145/3801961,Large Language Models for Combinatorial Optimi...,Francesca Da Ros; Michael Soprano; Luca Di Gas...,2026-03-16,2026,ACM Computing Surveys,review,This systematic review explores the applicatio...,; ; ; ; ;,8,True,NaN,https://doi.org/10.1145/3801961,Topic Modeling; Natural Language Processing Te...,University of Udine,en,"{""openalex_id"":""https:\/\/openalex.org\/W44153..."
4,4,openalex,https://openalex.org/W7124697892,https://doi.org/10.1007/s44443-025-00458-9,Inventory optimization under supply chain disr...,Ruijing Wu,2026-01-19,2026,Journal of King Saud University - Computer and...,article,Abstract This study pioneers the integration o...,; ; ; ; ; ; ;,0,True,NaN,https://doi.org/10.1007/s44443-025-00458-9,Supply Chain Resilience and Risk Management; S...,Shanghai International Studies University,en,"{""openalex_id"":""https:\/\/openalex.org\/W71246..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,721,openalex,https://openalex.org/W2009448384,https://doi.org/10.1016/j.indmarman.2005.01.004,"Formal governance mechanisms, relational gover...",Chwo‐Ming Joseph Yu; Tsai-Ju Liao; Zheng-Dao Lin,2005-06-10,2005,Industrial Marketing Management,article,NaN,; ; ; ; ; ; ;,188,False,NaN,https://doi.org/10.1016/j.indmarman.2005.01.004,Outsourcing and Supply Chain Management; Innov...,National Chengchi University,en,"{""openalex_id"":""https:\/\/openalex.org\/W20094..."
708,722,openalex,https://openalex.org/W2108380201,https://doi.org/10.1108/13673270510582983,A knowledge‐based system to support procuremen...,H.C.W. Lau; Andrew Ning; K.F. Pun; Kwai‐Sang C...,2005-02-01,2005,Journal of Knowledge Management,article,Purpose – To propose an infrastructure of a kn...,; ; ; ; ; ; ; ; ; ; ;,46,False,NaN,https://doi.org/10.1108/13673270510582983,Big Data and Business Intelligence,University of the West Indies; University of t...,en,"{""openalex_id"":""https:\/\/openalex.org\/W21083..."
709,723,openalex,https://openalex.org/W2003965326,https://doi.org/10.1016/s0925-5273(03)00128-2,The impact of forecasting methods on the bullw...,Xiaolong Zhang,2003-10-09,2003,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;,276,False,NaN,https://doi.org/10.1016/s0925-5273(03)00128-2,Supply Chain and Inventory Management; Forecas...,Fairleigh Dickinson University,en,"{""openalex_id"":""https:\/\/openalex.org\/W20039..."
710,724,openalex,https://openalex.org/W2070410573,https://doi.org/10.1016/s0925-5273(00)00156-0,Inventory management in supply chains: a reinf...,Ilaria Giannoccaro; Pierpaolo Pontrandolfo,2002-07-01,2002,International Journal of Production Economics,article,NaN,; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ;,221,False,NaN,https://doi.org/10.1016/s0925-5273(00)00156-0,Supply Chain and Inventory Management; Sustain...,Polytechnic University of Bari,en,"{""openalex_id"":""https:\/\/openalex.org\/W20704..."
711,725,openalex,https://openalex.org/W2170895557,https://doi.org/10.1016/s0377-2217(99)00237-4,A novel decomposition approach for on-line lot...,Emile Aarts; M.F. Reijnhoudt; H.P. Stehouwer; ...,2000-04-01,2000,European Journal of Operational Research,article,NaN,; ; ; ; ; ; ; ;,14,True,NaN,https://doi.org/10.1016/s0377-2217(99)00237-4,Supply Chain and Inventory Management; Consume...,Eindhoven University of Technology; Philips (N...,en,"{""openalex_id"":""https:\/\/openalex.org\/W21708..."

In [11]:
merged_df = snowball_out2[~snowball_out2["source_id"].isin(snowball_out1['source_id'])]
merged_df.to_csv("snowball_out.csv")
merged_df

Empty DataFrame
Columns: [Unnamed: 0, source_db, source_id, doi, title, authors, publication_date, publication_year, source_name, doc_type, abstract, keywords, cited_by_count, is_open_access, pdf_url, landing_url, categories, institutions, language, raw_json]
Index: []